#!/usr/bin/env bash
# This script installs and configures nginx web server
# Install nginx
sudo apt-get update
sudo apt-get install nginx
#listen at port 80
sudo ufw 'Nginx HTTP'
# Create a custom HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html
#testing nginx config
sudo nginx -t
# Restart nginx
sudo service nginx reload
