#!/usr/bin/env bash
# This script configures nginx to redirect /redirect_me to another page with a 301 Moved Permanently status
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

# 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/victormayowa permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# starting Nginx
sudo service nginx restart
