#!/usr/bin/env bash
# this script checks if an argument is passed

if [[ $# -eq 0 ]]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

ip_address="$1"

ping_result=$(ping -c 5 "$ip_address")

echo "$ping_result"
