#!/usr/bin/env bash
# updates the Nginx configuration file to change the port from 8080 to 80.
sed -Ei -e "s|8080|80|g" /etc/nginx/sites-enabled/default
service nginx restart
rm -f /var/run/nginx.pid
