#!/usr/bin/env bash
# This script displays a list of currently running processes.

# Use ps command to get the list of processes and display them in a user-oriented format
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
