#!/usr/bin/env bash
# shellcheck disable=SC2009
# This script displays lines containing the "bash" word, allowing you to easily get the PID of your Bash process.

# Use ps command to get the list of processes, filter lines containing "bash", and exclude the grep command itself
ps -e | grep "bash" | grep -v "grep"
