#!/usr/bin/env bash
# This script displays lines containing the "bash" word, allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009

# Use ps command to get the list of processes, filter lines containing "bash", and exclude the grep command itself
ps -aux --forest | grep "bash" | grep -v "grep"
