#!/usr/bin/env bash
# This script tells a story based on the content of the file /etc/passwd

while IFS=':' read -r username _ uid gid _ homedir shell; do
    passcode=$(grep -w "$username" /etc/shadow | cut -d':' -f2)
    echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $username"
done < /etc/passwd
