#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# It shows only the part of the name after the first dash

for file in *; do
    if [ -f "$file" ] && [ "${file:0:1}" != "." ]; then
        filename=${file#*-}  # Extracts the part after the first dash
        echo "$filename"
    fi
done
