#!/usr/bin/env bash
# This script updates the /etc/hosts file to configure localhost and facebook.com IP addresses.
cp /etc/hosts ~/hosts.new
echo "8.8.8.8	facebook.com" > ~/hosts.new
while read -r line
do
	line_arr=( $line )
	if [ "${line_arr[1]}" = "localhost" ]
	then
		echo '127.0.0.2	localhost' >> ~/hosts.new
	else
		echo "$line" >> ~/hosts.new
	fi
done < /etc/hosts
cp ~/hosts.new /etc/hosts
